# Generated by Django 5.2.1 on 2025-11-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_remove_persona_id_persona_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='fecha_adopcion',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='adopcion',
            unique_together={('id_persona', 'id_mascota')},
        ),
    ]
