# Generated by Django 5.2 on 2025-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0002_remove_persona_id_persona_id_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='id_persona',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
