# Generated by Django 5.2 on 2025-11-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0003_alter_persona_id_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default='personas/default.png', upload_to='personas/'),
        ),
    ]
