# Generated by Django 5.2 on 2025-11-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0007_remove_mascota_id_mascota_color_mascota_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='collar',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
