# Generated by Django 5.2 on 2025-11-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "adopciones",
            "0007_remove_mascota_id_mascota_color_mascota_descripcion_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="adopcion",
            name="imagen",
            field=models.ImageField(
                blank=True,
                default="adopciones/default.png",
                null=True,
                upload_to="adopciones/",
            ),
        ),
    ]
