# Generated by Django 5.2 on 2025-11-07 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopciones', '0008_adopcion_imagen'),
        ('adopciones', '0008_mascota_collar'),
    ]

    operations = [
    ]
